apt-mark unhold kubeadm && \
apt-get update && apt-get install -y kubeadm=1.19.0-00 && \
apt-mark hold kubeadm

apt-mark unhold kubelet kubectl && \
apt-get update && apt-get install -y kubelet=1.19.0-00 kubectl=1.19.0-00 && \
apt-mark hold kubelet kubectl

apt-mark unhold kubeadm && \
apt-get update && apt-get install -y kubeadm=1.19.0-00 && \
apt-mark hold kubeadm
kubectl get deploy -n admin2406 -o custom-columns --sort-by

/opt/admin2406_data

apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deploy
spec:
 replicas: 1
 selector:
  matchLabels:
   name: mypod1
 template:
  metadata:
   name: nginx-container
   labels:
    name: mypod1
  spec:
   containers:
    - name: nginx-container
	  image: nginx:1.16
   
 apt-mark unhold kubeadm && \
apt-get update && apt-get install -y kubeadm=1.19.0-00 && \
apt-mark hold kubeadm

apt-mark unhold kubeadm && \
apt-get update && apt-get install -y kubeadm=1.19.0-00 && \
apt-mark hold kubeadm

apt-mark unhold kubelet kubectl && \
apt-get update && apt-get install -y kubelet=1.19.0-00 kubectl=1.19.0-00 && \
apt-mark hold kubelet kubectl


/opt/etcd-backup.db

--cert-file=/etc/kubernetes/pki/etcd/server.crt
--trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
--key-file=/etc/kubernetes/pki/etcd/server.key

ETCDCTL_API=3 etcdctl --endpoints=https://[127.0.0.1]:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/server.crt --key=/etc/kubernetes/pki/etcd/server.key snapshot save /opt/etcd-backup.db
	 
	 
secret-1401

apiVersion: v1
kind: pod
metadata:
name: secret-1401
spec:
 containers:
  - name: secret-admin
    image: busybox
	command: ["/bin/sh"]
	args: ["-c", "sleep 4800;"]
	volumeMounts:
    - name: secret-volume
      mountPath: "/etc/secret-volume"
      readOnly: true
 volumes:
  - name: secret-volume
    secret:
      secretName: dotfile-secret
	  
	  
	  k get deploy -n admin2406 --sort-by=.metadata.name -o custom-columns="DEPLOYMENT:metadata.name, CONTAINER_IMAGE:spec.template.spec.containers[*].image, READY_REPLICAS:spec.replicas, NAMESPACE:metadata.namespace" >  /opt/admin2406_data
